# Generated by Django 3.0 on 2020-01-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('IdComuna', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Asunto', models.CharField(max_length=50)),
                ('Mensaje', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('IdEstado', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('IdGenero', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('IdProvincia', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('IdTamano', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('IdTipo', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('IdTipo', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('RutPersona', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Contrasena', models.CharField(max_length=50)),
                ('Tipo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('IdRaza', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
                ('IdTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoMascota')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('RutPersona', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=50)),
                ('IdComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('IdMascota', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Peso', models.IntegerField()),
                ('IdGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genero')),
                ('IdRaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raza')),
                ('IdTamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tamano')),
                ('RutPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='IdProvincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provincia'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('IdCita', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('IdEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado')),
                ('IdMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mascota')),
                ('IdTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoConsulta')),
            ],
        ),
    ]
