# Generated by Django 3.0 on 2020-01-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='IdEstado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
