# Generated by Django 3.0 on 2020-01-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200131_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
