# Generated by Django 3.0 on 2020-02-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fichadesparacitacion_fichavacunacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichavacunacion',
            name='IdMascota',
        ),
        migrations.DeleteModel(
            name='FichaDesparacitacion',
        ),
        migrations.DeleteModel(
            name='FichaVacunacion',
        ),
    ]
