# Generated by Django 3.0 on 2020-02-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fichadesparacitacion_fichavacunacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FichaDesparacitacion',
        ),
    ]
