# Generated by Django 3.0 on 2020-02-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_fichadesparacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDesparacitacion',
            fields=[
                ('IdFicha', models.IntegerField(primary_key=True, serialize=False)),
                ('FechaDesp', models.DateField()),
                ('Peso', models.IntegerField()),
                ('Medicamento', models.CharField(max_length=50)),
                ('Dosis', models.CharField(max_length=50)),
                ('FechaProxima', models.DateField()),
                ('IdMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mascota')),
            ],
        ),
    ]
