# Generated by Django 3.0 on 2020-02-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fichadesparacitacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
