# Generated by Django 3.0 on 2020-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='RutPersona',
            field=models.CharField(max_length=45),
        ),
    ]
