# Generated by Django 3.0 on 2020-02-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200213_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='RutPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Persona'),
        ),
    ]
